- name: Stress HPE Storage CSI
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:

  - name: Generate job List
    ansible.builtin.set_fact:
      thelist: "{{ range(0, max) | list }}"

  - name: Create Stateful Redis Deployment
    kubernetes.core.k8s:
      namespace: "{{ namespace }}"
      api_key: "{{ token }}"
      host: "{{ url }}"
      validate_certs: false
      state: present
      template: "templates/redis-create.yaml"
      # wait: true
      # wait_timeout: 600
    vars:
      checkpoint_namespace: "{{ item.namespace }}"
      checkpoint_pod: "{{ item.pod_id }}"
      checkpoint_container: "{{ item.container }}"
    register: create_job
    with_items: "{{ thelist }}"

  - name: Pause execution
    ansible.builtin.pause:
      prompt: "Hit a button to proceed and delete deployments"

  - name: Delete Stateful Redis Deployment
    kubernetes.core.k8s:
      namespace: "{{ namespace }}"
      api_key: "{{ token }}"
      host: "{{ url }}"
      validate_certs: false
      state: absent
      template: "templates/redis-delete.yaml"
      # wait: true
      # wait_timeout: 600
    vars:
      checkpoint_namespace: "{{ item.namespace }}"
      checkpoint_pod: "{{ item.pod_id }}"
      checkpoint_container: "{{ item.container }}"
    register: create_job
    with_items: "{{ thelist }}"
